# Generated by Django 5.2.10 on 2026-06-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbehavior',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('add_to_cart', 'Add To Cart'), ('buy', 'Buy'), ('rating', 'Rating'), ('search', 'Search')], max_length=20),
        ),
    ]
