# Generated by Django 5.2.10 on 2026-06-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_restructure_product_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
